
// A curated palette of common color names (lowercase)
export const COLOR_PALETTE = [
  'red',        'orange',    'yellow',    'green',    'blue',     'indigo',
  'violet',     'pink',      'purple',    'brown',    'black',    'white',
  'gray',       'grey',      'cyan',      'magenta',  'lime',     'maroon',
  'navy',       'olive',     'teal',      'silver',   'gold',     'beige',
  'coral',      'fuchsia',   'turquoise', 'salmon',   'plum',     'orchid',
  'khaki',      'crimson',   'azure',     'lavender', 'tan',      'aqua',
  'aquamarine', 'chocolate', 'ivory',     'mint',     'peachpuff'
];

export const FIRST_NAMES = [
  'Liam',        'Noah',       'Oliver',      'Theodore',   'James',
  'Henry',       'Mateo',      'Elijah',      'Lucas',      'William',
  'Benjamin',    'Levi',       'Ezra',        'Sebastian',  'Jack',
  'Daniel',      'Samuel',     'Michael',     'Ethan',      'Asher',
  'John',        'Hudson',     'Luca',        'Leo',        'Elias',
  'Owen',        'Alexander',  'Dylan',       'Santiago',   'Julian',
  'David',       'Joseph',     'Matthew',     'Luke',       'Jackson',
  'Maverick',    'Miles',      'Wyatt',       'Thomas',     'Isaac',
  'Jacob',       'Mason',      'Gabriel',     'Anthony',    'Carter',
  'Logan',       'Aiden',      'Grayson',     'Caleb',      'Cooper',
  'Charles',     'Roman',      'Josiah',      'Ezekiel',    'Thiago',
  'Isaiah',      'Joshua',     'Wesley',      'Jayden',     'Bennett',
  'Christopher', 'Nathan',     'Angel',       'Nolan',      'Waylon',
  'Cameron',     'Brooks',     'Andrew',      'Beau',       'Weston',
  'Rowan',       'Adrian',     'Lincoln',     'Enzo',       'Ian',
  'Kai',         'Christian',  'Axel',        'Aaron',      'Theo',
  'Silas',       'Walker',     'Jonathan',    'Leonardo',   'Everett',
  'Micah',       'Ryan',       'August',      'Gael',       'Robert',
  'Jose',        'Eli',        'Jeremiah',    'Luka',       'Amir',
  'Jaxon',       'Parker',     'Colton',      'Myles',      'Adam',
  'Atlas',       'Xavier',     'Easton',      'Jordan',     'Arthur',
  'Landon',      'Austin',     'Dominic',     'Adriel',     'Damian',
  'Vincent',     'River',      'Emiliano',    'Jace',       'Archer',
  'Lorenzo',     'Jameson',    'Nicholas',    'Emmett',     'Milo',
  'Harrison',    'Giovanni',   'Carson',      'George',     'Kayden',
  'Jonah',       'Greyson',    'Hunter',      'Graham',     'Luis',
  'Declan',      'Sawyer',     'Jasper',      'Ryder',      'Carlos',
  'Connor',      'Juan',       'Matteo',      'Dawson',     'Calvin',
  'Leon',        'Dean',       'Evan',        'Nathaniel',  'Diego',
  'Arlo',        'Bryson',     'Jason',       'Malachi',    'Elliot',
  'Zion',        'Emilio',     'Ivan',        'Hayden',     'Stetson',
  'Jude',        'Legend',     'Matias',      'Callum',     'Hayes',
  'Jett',        'Cole',       'Elliott',     'Jesus',      'Ace',
  'Beckett',     'Alan',       'Beckham',     'Jayce',      'Braxton',
  'Jaxson',      'Amari',      'Chase',       'Rhett',      'Max',
  'Charlie',     'Felix',      'Kingston',    'Judah',      'Antonio',
  'Emmanuel',    'Maxwell',    'Ryker',       'Alejandro',  'Nicolas',
  'Barrett',     'Jesse',      'Ashton',      'Miguel',     'Brayden',
  'Tyler',       'Peter',      'Camden',      'Zachary',    'Tatum',
  'Kevin',       'Andres',     'Finn',        'Justin',     'Tucker',
  'Bentley',     'Zayden',     'Messiah',     'Abraham',    'Alex',
  'Adonis',      'Kaiden',     'Timothy',     'Knox',       'Tate',
  'Caden',       'Ayden',      'Nico',        'Victor',     'Maddox',
  'Xander',      'Oscar',      'Colter',      'Joel',       'Abel',
  'Patrick',     'Rafael',     'Griffin',     'Brody',      'Jaziel',
  'Rory',        'Eithan',     'Edward',      'Riley',      'Brandon',
  'Milan',       'Richard',    'Malakai',     'Ismael',     'Kyrie',
  'Louis',       'Elian',      'Kairo',       'Cohen',      'Nash',
  'Grant',       'Callan',     'Dallas',      'Harvey',     'Muhammad',
  'Mark',        'Javier',     'Karter',      'Zayn',       'Crew',
  'Eric',        'Simon',      'Aziel',       'Cyrus',      'Gavin',
  'Marcus',      'Ronan',      'Derek',       'Avery',      'Omar',
  'Lane',        'Warren',     'Lennox',      'Paul',       'Blake',
  'Jeremy',      'Tristan',    'Lukas',       'Steven',     'Emerson',
  'Walter',      'Cade',       'Ellis',       'Otto',       'Phoenix',
  'Colt',        'Atticus',    'Kaleb',       'Israel',     'Tobias',
  'Holden',      'Saint',      'Romeo',       'Kenneth',    'Jorge',
  'Angelo',      'Remington',  'Paxton',      'Cody',       'Finley',
  'Kayson',      'Koa',        'Kash',        'Josue',      'Ares',
  'Hendrix',     'Bryce',      'Maximiliano', 'Zyaire',     'Reid',
  'Brian',       'Bodhi',      'Cruz',        'Kaden',      'Bryan',
  'Zane',        'Francisco',  'Martin',      'Brady',      'Casey',
  'Shepherd',    'Aidan',      'Baker',       'Malcolm',    'Jax',
  'Cash',        'Clayton',    'Kohen',       'Leonel',     'Cristian',
  'Bowen',       'Dante',      'Ali',         'Jaylen',     'Orion',
  'Briggs',      'Jensen',     'Dakota',      'Preston',    'Maximus',
  'Gideon',      'Erick',      'Archie',      'Colin',      'Sonny',
  'Shiloh',      'Mathias',    'Ezequiel',    'Sullivan',   'Joaquin',
  'Wade',        'King',       'Niko',        'Damien',     'Kade',
  'Bodie',       'Dariel',     'Luciano',     'Cayden',     'Andre',
  'Manuel',      'Fernando',   'Colson',      'Rhys',       'Cairo',
  'Anderson',    'Kyler',      'Onyx',        'Ibrahim',    'Cesar',
  'Travis',      'Santino',    'Callahan',    'Bradley',    'Baylor',
  'Banks',       'Russell',    'Desmond',     'Killian',    'Grady',
  'Rylan',       'Sterling',   'Kylo',        'Eduardo',    'Ricardo',
  'Wells',       'Stephen',    'Zander',      'Raymond',    'Hector',
  'Eliam',       'Edwin',      'Titus',       'Iker',       'Franklin',
  'Kamari',      'Marco',      'Spencer',     'Julius',     'Khalil',
  'Marshall',    'Wilder',     'Jared',       'Jaden',      'Kashton',
  'Jay',         'Karson',     'Mario',       'Ari',        'Remy',
  'Pedro',       'Sergio',     'Hugo',        'Prince',     'Winston',
  'Pablo',       'Forrest',    'Augustus',    'Kobe',       'Oakley',
  'Daxton',      'Tadeo',      'Sage',        'Apollo',     'Lawson',
  'Kian',        'Solomon',    'Chance',      'Kayce',      'Raphael',
  'Reed',        'Jake',       'Frederick',   'Armani',     'Hank',
  'Nehemiah',    'Royal',      'Kameron',     'Malik',      'Alijah',
  'Kane',        'Dalton',     'Lewis',       'Noel',       'Benson',
  'Sean',        'Clark',      'Miller',      'Kyle',       'Kieran',
  'Sutton',      'Fabian',     'Tanner',      'Marcelo',    'Rowen',
  'Isaias',      'Zayne',      'Nasir',       'Raiden',     'Francis',
  'Bo',          'Valentino',  'Rome',        'Damon',      'Reece',
  'Esteban',     'Edgar',      'Johnny',      'Kylian',     'Tyson',
  'Uriel',       'Royce',      'Cillian',     'Koda',       'Kyson',
  'Eden',        'Jalen',      'Frank',       'Conrad',     'Jasiah',
  'Matthias',    'Zaire',      'Corbin',      'Asa',        'Yusuf',
  'Erik',        'Callen',     'Kendrick',    'Odin',       'Brantley',
  'Rodrigo',     'Marcos',     'Gianni',      'Alexis',     'Lucian',
  'Denver',      'Sylas',      'Andy',        'Collin',     'Hezekiah',
  'Moshe',       'Finnegan',   'Ronin',       'Atreus',     'Adan',
  'Emanuel',     'Quinn',      'Mack',        'Leandro',    'Rocco',
  'Ruben',       'Ledger',     'Azariah',     'Donovan',    'Moses',
  'Kaizen',      'Elio',       'Leonidas',    'Lawrence',   'Tripp',
  'Ariel',       'Alonzo',     'Kaison',      'Lian',       'Devin',
  'Rio',         'Johnathan',  'Ayaan',       'Gunner',     'Jeffrey',
  'Philip',      'Samson',     'Moises',      'Lucca',      'Musa',
  'Camilo',      'Hamza',      'Ridge',       'Kolton',     'Morgan',
  'Troy',        'Kylan',      'Amiri',       'Boone',      'Makai',
  'Johan',       'Bruce',      'Dorian',      'Gregory',    'Pierce',
  'Roy',         'Drew',       'Clay',        'Caiden',     'Enrique',
  'Jamir',       'Leland',     'Mohamed',     'Alessandro', 'Deacon',
  'Augustine',   'Dominick',   'Roberto',     'Kasen',      'Zain',
  'Jonas',       'Emir',       'Seth',        'Saul',       'Jamari',
  'Lionel',      'Garrett',    'Jaiden',      'Fletcher',   'Scott',
  'Armando',     'Cassius',    'Kason',       'Zachariah',  'Ford',
  'Soren',       'Zaiden',     'Allen',       'Louie',      'Ronald',
  'Alden',       'Arturo',     'Caspian',     'Rayan',      'Major',
  'Arjun',       'Colby',      'Eliel',       'Krew',       'Ander',
  'Kenzo',       'Maximilian', 'Memphis',     'Nikolai',    'Samir',
  'Ocean',       'Anakin',     'Gerardo',     'Keegan',     'Maximo',
  'Mohammed',    'Kaysen',     'Julio',       'Mohammad',   'Gunnar',
  'Shane',       'Ozzy',       'Zakai',       'Sincere',    'Jaime',
  'Albert',      'Azriel',     'Izaiah',      'Jaxton',     'Raul',
  'Yosef',       'Creed',      'Rhodes',      'Princeton',  'Porter',
  'Cassian',     'Omari',      'Tru',         'Chosen',     'Reese',
  'Jayceon',     'Jayson',     'Jamie',       'Reign',      'Trevor',
  'Phillip',     'Boston',     'Kamden',      'Crue',       'Eliseo',
  'Colsen',      'Keanu',      'Mauricio',    'Salem',      'Dario',
  'Dax',         'Jase',       'Shawn',       'Vicente',    'Gustavo',
  'Danny',       'Mylo',       'Kyro',        'Wilson',     'Davis',
  'Jakari',      'Jakai',      'Truett',      'Hassan',     'Chris',
  'Sam',         'Brixton',    'Kyaire',      'Uriah',      'Azael',
  'Westley',     'Rocky',      'Peyton',      'Sevyn',      'Dilan',
  'Drake',       'Zaid',       'Roland',      'Dereck',     'Braylen',
  'Harlan',      'Taylor',     'Riggs',       'Ahmad',      'Cal',
  'Marvin',      'Donald',     'Leonard',     'Nathanael',  'Aarav',
  'Abdiel',      'Kareem',     'Corey',       'Emmitt',     'Wylder',
  'Koen',        'Junior',     'Zyair',       'Zayd',       'Dustin',
  'Wayne',       'Ahmed',      'Madden',      'Quincy',     'Bellamy',
  'Lachlan',     'Layton',     'Amias',       'Chaim',      'Layne',
  'Mac',         'Amos',       'Briar',       'Carmelo',    'Aries',
  'Bruno',       'Houston',    'Julien',      'Trace',      'Brock',
  'Yahya',       'Conor',      'Dennis',      'Duke',       'Abram',
  'Jefferson',   'Vincenzo',   'Izan',        'Lee',        'Finnley',
  'Brayan',      'Raylan',     'Enoch',       'Avyaan',     'Dexter',
  'Salvador',    'Case',       'Misael',      'Forest',     'Nikolas',
  'Westin',      'Braylon',    'Clyde',       'Ryland',     'Otis',
  'Tommy',       'Zeke',       'Yehuda',      'Tomas',      'Azrael',
  'Dutton',      'Flynn',      'Chandler',    'Idris',      'Zamir',
  'Ambrose',     'Franco',     'Huxley',      'Wes',        'Chozen',
  'Darius',      'Valentin',   'Alberto',     'Magnus',     'Roger',
  'Benicio',     'Brycen',     'Marcel',      'Ryatt',      'Zahir',
  'Keith',       'Rayden',     'Jamison',     'Teo',        'Skyler',
  'Blaze',       'Cayson',     'Hugh',        'Yahir',      'Cannon',
  'Yousef',      'Bjorn',      'Noe',         'Alonso',     'Alvaro',
  'Evander',     'Kenai',      'Aurelio',     'Jahmir',     'Lochlan',
  'Aron',        'Harry',      'Nelson',      'Ray',        'Alfredo',
  'Abdullah',    'Aryan',      'Conner',      'Lennon',     'Bridger',
  'Westyn',      'Jasiel',     'Quentin',     'Trey',       'Yael',
  'Alvin',       'Casen',      'Dakari',      'Rex',        'Damir',
  'Waylen',      'Izael',      'Jeremias',    'Kaiser',     'Kolson',
  'Ben',         'Kyree',      'Tony',        'Bode',       'Jesiah',
  'Eiden',       'Jaxxon',     'Jedidiah',    'Remi',       'Robin',
  'Santana',     'Kyren',      'Landen',      'Ezrah',      'Murphy',
  'Castiel',     'Boden',      'Derrick',     'Karim',      'Mustafa',
  'Rey',         'Rudy',       'Emery',       'Ignacio',    'Jettson',
  'Bear',        'Edison',     'Ricky',       'Ramon',      'Anders',
  'Gage',        'Guillermo',  'Santos',      'Kolter',     'Quinton',
  'Axton',       'Abner',      'Alfred',      'Darwin',     'Rohan',
  'Lance',       'Avi',        'Keaton',      'Orlando',    'Everest',
  'Jagger',      'Elisha',     'Heath',       'Jones',      'Thaddeus',
  'Allan',       'Cason',      'Douglas',     'Issac',      'Kenji',
  'Matheo',      'Ty',         'Asaiah',      'Jimmy',      'Arian',
  'Ozias',       'Leroy',      'Neil',        'Watson',     'Agustin',
  'Bryer',       'Jerry',      'Dillon',      'Eren',       'Eugene',
  'Ayan',        'Melvin',     'Nixon',       'Reuben',     'Stanley',
  'Grey',        'Loyal',      'Alec',        'Casper',     'Dane',
  'Azaiah',      'Byron',      'Joe',         'Emory',      'Zaylen',
  'Massimo',     'Trenton',    'Gatlin',      'Joey',       'Benny',
  'Jon',         'Jrue',       'Gian',        'Seven',      'Colten',
  'Ernesto',     'Fisher',     'Teddy',       'Kaisen',     'Zechariah',
  'Darian',      'Salvatore',  'Jericho',     'Mitchell',   'Alistair',
  'Calum',       'Van',        'Zev',         'Langston',   'Mccoy',
  'Ulises',      'Lucien',     'Benedict',    'Carlo',      'Coleson',
  'Meir',        'Henrik',     'Jiraiya',     'Kellan',     'Alfonso',
  'Azai',        'Campbell',   'Kylen',       'Felipe',     'Leif',
  'Rowdy',       'Curtis',     'Ameer',       'Kiaan',      'Maurice',
  'Krue',        'Shimon',     'Zyon',        'Damari',     'Jairo',
  'Khalid',      'Kabir',      'Jireh',       'Mathew',     'Shepard',
  'Eddie',       'Isael',      'Arden',       'Cedric',     'Nazir',
  'Alessio',     'Khai',       'Marcellus',   'Wesson',     'Yisroel',
  'Zymir',       'Landyn',     'Darren',      'Legacy',     'Devon',
  'Judson',      'Vihaan',     'Yitzchok',    'Zen',        'Dangelo',
  'Adler',       'Aspen',      'Brodie',      'Kase',       'Khaza',
  'Mordechai',   'Dash',       'Makari',      'Neo',        'Zavier',
  'Evren',       'Imran',      'Laith',       'Cain',       'Ira',
  'Osiris',      'Shlomo',     'Yaakov',      'Ephraim',    'Shmuel',
  'Wallace',     'Yeshua',     'Kannon',      'Kingsley',   'Noa',
  'True',        'Ermias',     'Harold',      'Joziah',     'Rene',
  'Truce',       'Aldo',       'Dimitri',     'Halo',       'Ronnie',
  'Vance',       'Aden',       'Ishaan',      'Kace',       'Stefan'
];
export const LAST_NAMES = [
  'Smith',      'Johnson',   'Williams',   'Brown',     'Jones',
  'Garcia',     'Miller',    'Davis',      'Rodriguez', 'Martinez',
  'Hernandez',  'Lopez',     'Gonzalez',   'Wilson',    'Anderson',
  'Thomas',     'Taylor',    'Moore',      'Jackson',   'Martin',
  'Lee',        'Perez',     'Thompson',   'White',     'Harris',
  'Sanchez',    'Clark',     'Ramirez',    'Lewis',     'Robinson',
  'Walker',     'Young',     'Allen',      'King',      'Wright',
  'Scott',      'Torres',    'Nguyen',     'Hill',      'Flores',
  'Green',      'Adams',     'Nelson',     'Baker',     'Hall',
  'Rivera',     'Campbell',  'Mitchell',   'Carter',    'Roberts',
  'Gomez',      'Phillips',  'Evans',      'Turner',    'Diaz',
  'Parker',     'Cruz',      'Edwards',    'Collins',   'Reyes',
  'Stewart',    'Morris',    'Morales',    'Murphy',    'Cook',
  'Rogers',     'Gutierrez', 'Ortiz',      'Morgan',    'Cooper',
  'Peterson',   'Bailey',    'Reed',       'Kelly',     'Howard',
  'Ramos',      'Kim',       'Cox',        'Ward',      'Richardson',
  'Watson',     'Brooks',    'Chavez',     'Wood',      'James',
  'Bennett',    'Gray',      'Mendoza',    'Ruiz',      'Hughes',
  'Price',      'Alvarez',   'Castillo',   'Sanders',   'Patel',
  'Myers',      'Long',      'Ross',       'Foster',    'Jimenez',
  'Powell',     'Jenkins',   'Perry',      'Russell',   'Sullivan',
  'Bell',       'Coleman',   'Butler',     'Henderson', 'Barnes',
  'Gonzales',   'Fisher',    'Vasquez',    'Simmons',   'Romero',
  'Jordan',     'Patterson', 'Alexander',  'Hamilton',  'Graham',
  'Reynolds',   'Griffin',   'Wallace',    'Moreno',    'West',
  'Cole',       'Hayes',     'Bryant',     'Herrera',   'Gibson',
  'Ellis',      'Tran',      'Medina',     'Aguilar',   'Stevens',
  'Murray',     'Ford',      'Castro',     'Marshall',  'Owens',
  'Harrison',   'Fernandez', 'Mcdonald',   'Woods',     'Washington',
  'Kennedy',    'Wells',     'Vargas',     'Henry',     'Chen',
  'Freeman',    'Webb',      'Tucker',     'Guzman',    'Burns',
  'Crawford',   'Olson',     'Simpson',    'Porter',    'Hunter',
  'Gordon',     'Mendez',    'Silva',      'Shaw',      'Snyder',
  'Mason',      'Dixon',     'Munoz',      'Hunt',      'Hicks',
  'Holmes',     'Palmer',    'Wagner',     'Black',     'Robertson',
  'Boyd',       'Rose',      'Stone',      'Salazar',   'Fox',
  'Warren',     'Mills',     'Meyer',      'Rice',      'Schmidt',
  'Garza',      'Daniels',   'Ferguson',   'Nichols',   'Stephens',
  'Soto',       'Weaver',    'Ryan',       'Gardner',   'Payne',
  'Grant',      'Dunn',      'Kelley',     'Spencer',   'Hawkins',
  'Arnold',     'Pierce',    'Vazquez',    'Hansen',    'Peters',
  'Santos',     'Hart',      'Bradley',    'Knight',    'Elliott',
  'Cunningham', 'Duncan',    'Armstrong',  'Hudson',    'Carroll',
  'Lane',       'Riley',     'Andrews',    'Alvarado',  'Ray',
  'Delgado',    'Berry',     'Perkins',    'Hoffman',   'Johnston',
  'Matthews',   'Pena',      'Richards',   'Contreras', 'Willis',
  'Carpenter',  'Lawrence',  'Sandoval',   'Guerrero',  'George',
  'Chapman',    'Rios',      'Estrada',    'Ortega',    'Watkins',
  'Greene',     'Nunez',     'Wheeler',    'Valdez',    'Harper',
  'Burke',      'Larson',    'Santiago',   'Maldonado', 'Morrison',
  'Franklin',   'Carlson',   'Austin',     'Dominguez', 'Carr',
  'Lawson',     'Jacobs',    'O’Brien',    'Lynch',     'Singh',
  'Vega',       'Bishop',    'Montgomery', 'Oliver',    'Jensen',
  'Harvey',     'Freeman',   'Bill',       'Zhou',      'Buchanan'
];

// A compact list of common world cities
export const CITY_LIST = [
  'New York',    'Los Angeles',    'Chicago',    'Houston',  'Phoenix',
  'London',      'Manchester',     'Birmingham', 'Glasgow',  'Liverpool',
  'Paris',       'Marseille',      'Lyon',       'Toulouse', 'Nice',
  'Berlin',      'Munich',         'Frankfurt',  'Hamburg',  'Cologne',
  'Tokyo',       'Osaka',          'Nagoya',     'Sapporo',  'Fukuoka',
  'Beijing',     'Shanghai',       'Guangzhou',  'Shenzhen', 'Chengdu',
  'Sydney',      'Melbourne',      'Brisbane',   'Perth',    'Adelaide',
  'Toronto',     'Vancouver',      'Montreal',   'Calgary',  'Ottawa',
  'São Paulo',   'Rio de Janeiro', 'Brasília',   'Salvador', 'Fortaleza',
  'Mexico City', 'Guadalajara',    'Monterrey',  'Puebla',   'Tijuana',
  'Dubai',       'Abu Dhabi',      'Doha',       'Istanbul', 'Moscow',
  'Tehran',      'Baghdad',        'Riyadh',     'Cairo',    'Lagos',
  'Isfahan',     'Mashhad',        'Tabriz',     'Shiraz',   'Kerman',
  'Jakarta',     'Surabaya',       'Bandung',    'Medan',    'Semarang'
];

// A compact list of country names
export const COUNTRY_LIST = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

// Common email domains for fake addresses
export const EMAIL_DOMAINS = [
  'example.com', 'test.com', 'mail.com', 'gmail.com', 'yahoo.com',
  'outlook.com', 'hotmail.com', 'proton.me', 'icloud.com'
];

// Weekday names (English)
export const WEEKDAYS = [
  'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'
];

// Month names (English)
export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',
  'September', 'October', 'November', 'December'
];
