import type { CollectedResults, TestRunResult, TestStepResult } from './reportCollector';

export interface ReportMarkdownOptions {
  suiteName?: string;
  includeDetails?: boolean;
}

function formatDuration(ms?: number): string {
  if (ms == null || ms < 0) {
    return '0.000s';
  }
  return (ms / 1000).toFixed(3) + 's';
}

function escapeMdTable(s: string): string {
  return String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function buildStepRow(step: TestStepResult, index: number): string {
  const name = escapeMdTable(step.title || `step-${step.stepIndex}`);
  const icon = step.status === 'passed' ? '✓' : '✗';
  const result = `${icon} ${step.status}`;
  const duration = step.durationMs != null ? formatDuration(step.durationMs) : '';
  return `| ${index + 1} | ${name} | ${step.stepType} | ${result} | ${duration} |`;
}

function buildFailureDetails(step: TestStepResult): string {
  const name = step.title || `step-${step.stepIndex}`;
  let md = `\n<details>\n<summary>✗ ${name}</summary>\n\n`;
  if (step.expected != null) {
    md += `- **Expected:** ${step.expected}\n`;
  }
  if (step.actual != null) {
    md += `- **Actual:** ${step.actual}\n`;
  }
  if (step.comparison) {
    md += `- **Operator:** ${step.comparison}\n`;
  }
  md += `\n</details>\n`;
  return md;
}

function buildSuiteSection(run: TestRunResult, index: number, includeDetails: boolean): string {
  const name = run.displayName || run.filePath || `test-${index}`;
  let md = `\n## ${name}\n\n`;
  md += `| # | Test | Type | Result | Duration |\n`;
  md += `|---|------|------|--------|----------|\n`;
  for (let i = 0; i < run.steps.length; i++) {
    md += buildStepRow(run.steps[i], i) + '\n';
  }
  if (run.steps.length === 0) {
    md += `| | *No test steps* | | | |\n`;
  }

  if (includeDetails) {
    const failedSteps = run.steps.filter(s => s.status === 'failed');
    for (const step of failedSteps) {
      md += buildFailureDetails(step);
    }
  }

  return md;
}

export function generateReportMarkdown(results: CollectedResults, options?: ReportMarkdownOptions): string {
  const runs = results.testRuns;
  const suiteName = options?.suiteName || results.suiteRun?.suitePath || 'multimeter';
  const includeDetails = options?.includeDetails !== false;
  const totalTests = runs.reduce((sum, r) => sum + r.steps.length, 0);
  const totalPassed = runs.reduce((sum, r) => sum + r.steps.filter(s => s.status === 'passed').length, 0);
  const totalFailed = runs.reduce((sum, r) => sum + r.steps.filter(s => s.status === 'failed').length, 0);
  const totalTime = formatDuration(
    results.suiteRun?.durationMs ?? runs.reduce((sum, r) => sum + (r.durationMs || 0), 0)
  );

  let md = `# Test Report: ${suiteName}\n\n`;

  if (results.suiteRun?.startedAt) {
    md += `**Timestamp:** ${new Date(results.suiteRun.startedAt).toISOString()}  \n`;
  }
  md += `**Duration:** ${totalTime}  \n`;
  md += `**Result:** ${totalPassed} passed, ${totalFailed} failed, ${totalTests} total\n`;

  if (results.suiteRun?.cancelled) {
    md += `\n> ⚠ **Run was cancelled**\n`;
  }

  for (let i = 0; i < runs.length; i++) {
    md += buildSuiteSection(runs[i], i, includeDetails);
  }

  md += `\n---\n*Generated by Multimeter*\n`;
  return md;
}
