import { generateReportMarkdown } from './reportMarkdown';
import type { CollectedResults, TestRunResult, TestStepResult } from './reportCollector';

function makeStep(overrides: Partial<TestStepResult> = {}): TestStepResult {
  return {
    stepIndex: 0,
    stepType: 'check',
    status: 'passed',
    comparison: '==',
    timestamp: 1709720000000,
    ...overrides,
  };
}

function makeRun(overrides: Partial<TestRunResult> = {}): TestRunResult {
  return {
    runId: 'run-1',
    result: 'passed',
    steps: [],
    ...overrides,
  };
}

describe('generateReportMarkdown', () => {
  it('generates Markdown with summary header and table', () => {
    const results: CollectedResults = {
      type: 'test',
      testRuns: [
        makeRun({
          displayName: 'test.mmt',
          durationMs: 500,
          steps: [
            makeStep({ title: 'status == 200', durationMs: 100 }),
            makeStep({ title: 'body.ok', durationMs: 50 }),
          ],
        }),
      ],
    };

    const md = generateReportMarkdown(results);
    expect(md).toContain('# Test Report: multimeter');
    expect(md).toContain('2 passed, 0 failed, 2 total');
    expect(md).toContain('| # | Test | Type | Result |');
    expect(md).toContain('status == 200');
    expect(md).toContain('✓ passed');
  });

  it('generates one table per suite for multiple test runs', () => {
    const results: CollectedResults = {
      type: 'suite',
      suiteRun: {
        runId: 'suite-1',
        suitePath: 'suite.mmt',
        startedAt: 1709720000000,
        durationMs: 3000,
        success: true,
        totalRunnable: 2,
        testRuns: [],
      },
      testRuns: [
        makeRun({ displayName: 'test-a.mmt', steps: [makeStep({ title: 'a' })] }),
        makeRun({ displayName: 'test-b.mmt', steps: [makeStep({ title: 'b' })] }),
      ],
    };

    const md = generateReportMarkdown(results);
    expect(md).toContain('## test-a.mmt');
    expect(md).toContain('## test-b.mmt');
    expect(md).toContain('# Test Report: suite.mmt');
  });

  it('generates details blocks for failed steps', () => {
    const results: CollectedResults = {
      type: 'test',
      testRuns: [
        makeRun({
          displayName: 'test.mmt',
          steps: [
            makeStep({
              title: 'name == John',
              status: 'failed',
              actual: 'Jane',
              expected: 'John',
              comparison: '==',
            }),
          ],
        }),
      ],
    };

    const md = generateReportMarkdown(results);
    expect(md).toContain('<details>');
    expect(md).toContain('<summary>✗ name == John</summary>');
    expect(md).toContain('**Expected:** John');
    expect(md).toContain('**Actual:** Jane');
    expect(md).toContain('**Operator:** ==');
    expect(md).toContain('</details>');
    expect(md).toContain('✗ failed');
  });

  it('handles empty test (no steps)', () => {
    const results: CollectedResults = {
      type: 'test',
      testRuns: [makeRun({ displayName: 'empty.mmt' })],
    };

    const md = generateReportMarkdown(results);
    expect(md).toContain('*No test steps*');
    expect(md).toContain('0 passed, 0 failed, 0 total');
  });

  it('escapes pipe characters in table cells', () => {
    const results: CollectedResults = {
      type: 'test',
      testRuns: [
        makeRun({
          displayName: 'test.mmt',
          steps: [makeStep({ title: 'a | b | c' })],
        }),
      ],
    };

    const md = generateReportMarkdown(results);
    expect(md).toContain('a \\| b \\| c');
  });

  it('omits details when includeDetails is false', () => {
    const results: CollectedResults = {
      type: 'test',
      testRuns: [
        makeRun({
          displayName: 'test.mmt',
          steps: [
            makeStep({ title: 'fail', status: 'failed', actual: '1', expected: '2' }),
          ],
        }),
      ],
    };

    const md = generateReportMarkdown(results, { includeDetails: false });
    expect(md).not.toContain('<details>');
    expect(md).toContain('✗ failed');
  });

  it('includes cancelled warning', () => {
    const results: CollectedResults = {
      type: 'suite',
      suiteRun: {
        runId: 'suite-1',
        startedAt: 1709720000000,
        success: false,
        cancelled: true,
        totalRunnable: 5,
        testRuns: [],
      },
      testRuns: [],
    };

    const md = generateReportMarkdown(results);
    expect(md).toContain('Run was cancelled');
  });

  it('uses suiteName option', () => {
    const results: CollectedResults = {
      type: 'test',
      testRuns: [makeRun()],
    };

    const md = generateReportMarkdown(results, { suiteName: 'My Suite' });
    expect(md).toContain('# Test Report: My Suite');
  });

  it('ends with Generated by Multimeter', () => {
    const results: CollectedResults = {
      type: 'test',
      testRuns: [makeRun()],
    };

    const md = generateReportMarkdown(results);
    expect(md).toContain('*Generated by Multimeter*');
  });
});
