import type { MmtFileType } from "mmt-core/mmtFileType";

export type NotypeSampleType = MmtFileType;

export interface NotypeSample {
  type: NotypeSampleType;
  title: string;
  description: string;
  content: string;
}

const DOCS_BASE = "https://mmt.dev/docs";
const DEMOS_BASE = "https://mmt.dev/demos";

/** Site docs + demo-page section for each gallery file type. */
export const notypeHelpLinks: Record<NotypeSampleType, { docsUrl: string; demoUrl: string }> = {
  api: {
    docsUrl: `${DOCS_BASE}/files/api`,
    demoUrl: `${DEMOS_BASE}#api`,
  },
  env: {
    docsUrl: `${DOCS_BASE}/files/env`,
    demoUrl: `${DEMOS_BASE}#environment`,
  },
  test: {
    docsUrl: `${DOCS_BASE}/files/test`,
    demoUrl: `${DEMOS_BASE}#test`,
  },
  suite: {
    docsUrl: `${DOCS_BASE}/files/suite`,
    demoUrl: `${DEMOS_BASE}#suite`,
  },
  loadtest: {
    docsUrl: `${DOCS_BASE}/files/loadtest`,
    demoUrl: `${DEMOS_BASE}#load-test`,
  },
  doc: {
    docsUrl: `${DOCS_BASE}/files/doc`,
    demoUrl: `${DEMOS_BASE}#documentation`,
  },
  server: {
    docsUrl: `${DOCS_BASE}/files/server`,
    demoUrl: `${DEMOS_BASE}#mock-server`,
  },
  judge: {
    docsUrl: `${DOCS_BASE}/files/judge`,
    demoUrl: `${DEMOS_BASE}#judge`,
  },
  report: {
    docsUrl: `${DOCS_BASE}/files/report`,
    demoUrl: `${DEMOS_BASE}#report`,
  },
};

/** First gallery sample per type — used when picking a type from the icon row. */
export function notypeStarterContent(type: NotypeSampleType): string {
  const sample = notypeSamples.find(entry => entry.type === type);
  return sample?.content ?? `type: ${type}\n`;
}

export const notypeSamples: NotypeSample[] = [
  {
    type: "api",
    title: "HTTP GET request",
    description: "Call an endpoint.",
    content: `type: api
url: https://test.mmt.dev
method: get
`,
  },
  {
    type: "api",
    title: "HTTP POST JSON request",
    description: "Send a JSON payload to server.",
    content: `type: api
url: https://test.mmt.dev/echo
method: post
format: json
body:
  message: hello
`,
  },
  {
    type: "env",
    title: "Environment variables",
    description: "Store shared values.",
    content: `type: env
variables:
  base_url: https://test.mmt.dev
  api_key: your-api-key-here
`,
  },
  {
    type: "test",
    title: "HTTP status check test",
    description: "Send a request and assert the status code.",
    content: `type: test
steps:
  - http: https://test.mmt.dev
    expect:
      status: 200
`,
  },
  {
    type: "test",
    title: "HTTP POST and verify",
    description: "Send a POST request and check echoed fields.",
    content: `type: test
steps:
  - http: https://test.mmt.dev/echo
    method: post
    body:
      message: hello
    expect:
      status: 200
      body.body.message: hello
`,
  },
  {
    type: "suite",
    title: "Basic suite",
    description: "Run multiple test files together.",
    content: `type: suite
items:
  - path/to/first_test.mmt
  - path/to/second_test.mmt
`,
  },
  {
    type: "loadtest",
    title: "Load test",
    description: "Run a test file with multiple workers.",
    content: `type: loadtest
threads: 5
repeat: 30s
test: ./my_test.mmt
`,
  },
  {
    type: "doc",
    title: "API documentation",
    description: "Generate docs from API files in the project.",
    content: `type: doc
sources:
  - api
`,
  },
  {
    type: "server",
    title: "Mock Server",
    description: "Serve canned responses for local development.",
    content: `type: server
port: 9099
cors: true
endpoints:
  - method: get
    path: /hello
    status: 200
    format: json
    body:
      message: hello
`,
  },
  {
    type: "judge",
    title: "AI Judge (Ollama)",
    description: "Local LLM judge for non-deterministic responses.",
    content: `type: judge
engine: ollama
model: qwen2.5-coder:7b
url: http://127.0.0.1:11434
options:
  temperature: 0
  timeout: 120s
`,
  },
  {
    type: "report",
    title: "Test report",
    description: "Structured results view (usually generated by a run).",
    content: `type: report
kind: functional
name: example.mmt
overview:
  timestamp: "2026-01-01T00:00:00.000Z"
  duration: 1.2s
  checks: 2
  passed: 2
  failed: 0
checks:
  - name: status == 200
    type: check
    result: passed
  - name: body.message == hello
    type: check
    result: passed
`,
  },
];
