import type { Type } from "mmt-core/CommonData";

export type NotypeSampleType = Exclude<Type, null | "csv">;

export interface NotypeSample {
  type: NotypeSampleType;
  title: string;
  description: string;
  codicon: string;
  content: string;
}

const DOCS_BASE = "https://github.com/mshobeyri/multimeter/blob/dev/docs";
const DEMOS_BASE = "https://mmt.dev/demos";

/** GitHub docs + demo-page section for each gallery file type. */
export const notypeHelpLinks: Record<NotypeSampleType, { docsUrl: string; demoUrl: string }> = {
  api: {
    docsUrl: `${DOCS_BASE}/api-mmt.md`,
    demoUrl: `${DEMOS_BASE}#api`,
  },
  env: {
    docsUrl: `${DOCS_BASE}/environment-mmt.md`,
    demoUrl: `${DEMOS_BASE}#environment`,
  },
  test: {
    docsUrl: `${DOCS_BASE}/test-mmt.md`,
    demoUrl: `${DEMOS_BASE}#test`,
  },
  suite: {
    docsUrl: `${DOCS_BASE}/suite-mmt.md`,
    demoUrl: `${DEMOS_BASE}#suite`,
  },
  loadtest: {
    docsUrl: `${DOCS_BASE}/loadtest-mmt.md`,
    demoUrl: `${DEMOS_BASE}#load-test`,
  },
  doc: {
    docsUrl: `${DOCS_BASE}/doc-mmt.md`,
    demoUrl: `${DEMOS_BASE}#documentation`,
  },
  server: {
    docsUrl: `${DOCS_BASE}/mock-server.md`,
    demoUrl: `${DEMOS_BASE}#mock-server`,
  },
  report: {
    docsUrl: `${DOCS_BASE}/reports.md`,
    demoUrl: `${DEMOS_BASE}#report`,
  },
};

export const notypeSamples: NotypeSample[] = [
  {
    type: "api",
    title: "Simple GET request",
    description: "Call an endpoint and inspect the response.",
    codicon: "globe",
    content: `type: api
title: Simple GET request
url: https://test.mmt.dev  # change to your API URL
method: get
`,
  },
  {
    type: "api",
    title: "POST JSON body",
    description: "Send a JSON payload to an echo server.",
    codicon: "send",
    content: `type: api
title: POST JSON body
url: https://test.mmt.dev/echo
method: post
format: json
body:
  message: hello
`,
  },
  {
    type: "env",
    title: "Environment variables",
    description: "Store shared values like base URL and API keys.",
    codicon: "server-environment",
    content: `type: env
variables:
  base_url: https://test.mmt.dev  # your API base URL
  api_key: your-api-key-here
`,
  },
  {
    type: "test",
    title: "HTTP status check",
    description: "Send a request and assert the status code.",
    codicon: "beaker",
    content: `type: test
title: HTTP status check
steps:
  - http: https://test.mmt.dev
    title: Check status
    expect:
      status: 200
`,
  },
  {
    type: "test",
    title: "POST and verify body",
    description: "Send a POST request and check echoed fields.",
    codicon: "check",
    content: `type: test
title: POST and verify body
steps:
  - http: https://test.mmt.dev/echo
    title: Post echo
    method: post
    body:
      message: hello
    expect:
      status: 200
      body.body.message: hello
`,
  },
  {
    type: "suite",
    title: "Basic suite",
    description: "Run multiple test files together.",
    codicon: "list-tree",
    content: `type: suite
title: My test suite
items:
  - path/to/first_test.mmt  # add your test files here
  - path/to/second_test.mmt
`,
  },
  {
    type: "loadtest",
    title: "Load test",
    description: "Run a test file with multiple workers.",
    codicon: "pulse",
    content: `type: loadtest
title: Basic load test
threads: 5
repeat: 30s
test: ./my_test.mmt  # path to your test file
`,
  },
  {
    type: "doc",
    title: "API documentation",
    description: "Generate docs from API files in the project.",
    codicon: "book",
    content: `type: doc
title: API Documentation
sources:
  - api # Pass the folder contains your api .mmt files
`,
  },
  {
    type: "server",
    title: "Mock server",
    description: "Serve canned responses for local development.",
    codicon: "server",
    content: `type: server
title: Mock server
port: 9099
cors: true
endpoints:
  - method: get
    path: /hello
    status: 200
    format: json
    body:
      message: hello
`,
  },
  {
    type: "report",
    title: "Test report",
    description: "Structured results view (usually generated by a run).",
    codicon: "output",
    content: `type: report
kind: functional
name: example.mmt
overview:
  timestamp: "2026-01-01T00:00:00.000Z"
  duration: 1.2s
  checks: 2
  passed: 2
  failed: 0
checks:
  - name: status == 200
    type: check
    result: passed
  - name: body.message == hello
    type: check
    result: passed
`,
  },
];

export const notypeTypeIcons: Record<NotypeSampleType, string> = {
  api: "globe",
  env: "server-environment",
  test: "beaker",
  suite: "list-tree",
  loadtest: "pulse",
  doc: "book",
  server: "server",
  report: "output",
};
